### ISSUE TITLE
Create preview table when dictionaries across rows are not consistent

### ISSUE THREAD

**Issue by myyong** [wrattler/wrattler#70]
When creating the dts dataframe in R [cleanEHR](https://github.com/wrattler/wrattler/blob/cleanEHR_export_dataset_R/client/public/cleanEHR.md), we have rows with inconsistent dictionaries. We are currently using the first row's keys to generate headers but this is not the superset of the keys or even a common set of keys.

Therefore, there are missing keys 
- where a key does not appear in the first row but exists elsewhere
- a key in subsequent rows is missing, which yields `undefined` when we try to access it.

For example, row `0' has
```json
{X1: 1, X73: 73, X71: 71, X71.1: 71, X79: 79, X31: 31, X31.1: 31, X31.2: 31, X31.3: 31}
```
And row `1` has
```json
{X1: 30, X73: 60.0714, X71: 13.75, X71.1: 68, X79: 90.75, X107.4: 103, X92: 99, X121: 114}
```

Any ideas which approach we should take to solve this?

**Comment by tpetricek** [comment]
Uh oh!

I think we should not allow this sort of data to get into data store. We should always only store tables that have consistent row keys - in this case, I think we should just "fix" the data frame before storing it in data store and fill the missing data with `null`.

(I think we might want to reconsider how we store the data - and if we switch to JSON into something binary, then we will definitely need to keep consistent row keys).

**Comment by tpetricek** [comment]
- When R service stores data frames in data store, it should turn `NA` and `NaN` into JSON `null` value rather than omitting the key. (We'll use JSON `null` to represent missing/not a number; R distinguishes between the two, but we'll see if we can get away without that for now.) 

 - Check with Giovanni to make sure the difference between `NA` and `NaN` in `dts` data frame does not matter. [EDIT: No, it does not, because they both become missing in the saved CSV file.]

 - Make sure `null` from data store loads correctly in Python (we should first check what happens in original analysis - do the `NA` and `NaN` values just become missing in Python?).

**Comment by nbarlowATI** [comment]
This is all resolved now with consistent use of Na/NaN/None/null in the language services and the datastore.
